use_frameworks!

target 'YXKit_Example' do
#  pod 'YXKit', :path => '../'

  target 'YXKit_Tests' do
    inherit! :search_paths

#    pod 'Specta'
#    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
#    pod 'Expecta+Snapshots'
  end
end
